language: node_js
node_js:
  - "8"
deploy:
  provider: npm
  email: "kayson@huida.cn"
  api_token:
    secure: "h3xOcVFS/KxEfyfIMCmMSVlc13va3LIJVW1Om7xNuG/8XSVWXkPkf8QzsaUMyPw98olkpr3QPqPOcNvHlg6wE9QGIodH48qmfTccY+0Nel+MywMxmD4CrN7e6loXP5DLBJPI3aNH74ukXNf2DUoHRkp+laNY92qUYbi9TzYE18A+fchE6pKnTIHq7QyuJJCJXObTv7Ni6ounUndIij/3mz1XCAAUc225/p2ygrm3Sqi/jIA8Ofmb2s/YkF+FVZ2RoISyd6+7DpUbifTIY7rrMD3mnC/kilWg2TVcG6tTfVefkmgHZFhZbAdeG+lwOt0lqiqAMeYkmyH+qQ8VMs6U0oFDbWnXDGQTK6X4UcBupcUoNj1zAz6UtiWKSPRky8XeGehSuaZlziyWX/4F35IW+2rjezWgBqtK8EzkRdRAH3TRBUmkaA0Dy1CSI7InfWXCJ8I+WunK+VoE4fb1RDCaV/izLIELIk+hqjx7TFjw1ylEgKdmkB347nsApwzW3DmTz5a5Xs1/DgNhoVFRUPWGYOaDsYChre/OFwMdGuRdRX+qNkP/QYR3TH2DNH5JY2rl95tZsieNmj/yuUlr9kaIKfWCSY0yl147ZI+JE7gpuE1R9IYH4m8PoGUQlzKvA5SOR07UkQsVSkSJLTYj6QEqvXBkTLOS8ritveL3EDl+cDM="
  on:
    branch: master
    tags: true